/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotelide;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Msys
 */
public class EmRes extends javax.swing.JFrame {

    /** Creates new form EmRes */
    public EmRes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        searchCustomer = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        panel16 = new java.awt.Panel();
        panel6 = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1060, 560));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(228, 237, 237));
        jPanel1.setPreferredSize(new java.awt.Dimension(645, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(222, 215, 215));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/Buildingsss.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel19.setBackground(new java.awt.Color(222, 215, 215));
        jPanel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel19mouseenered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel19exited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 102, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/Occupied-Bed-iconn.png"))); // NOI18N
        jLabel13.setText("Rooms");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jPanel4.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 190, 50));

        jPanel15.setBackground(new java.awt.Color(222, 215, 215));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel15mouseenered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel15exited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 102, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/Search-icon.png"))); // NOI18N
        jLabel12.setText("Customers");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jPanel4.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 190, 50));

        jPanel9.setBackground(new java.awt.Color(222, 215, 215));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseenered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/Plus-icon-Symbol-instance.png"))); // NOI18N
        jLabel1.setLabelFor(jPanel19);
        jLabel1.setText("New Customer");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, -1));

        jPanel16.setBackground(new java.awt.Color(222, 215, 215));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel16jMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel16mouseenered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel16exited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 102, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/req.png"))); // NOI18N
        jLabel15.setText("Requests");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(0, 82, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jPanel4.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 190, -1));

        jPanel25.setBackground(new java.awt.Color(222, 215, 215));
        jPanel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel25jPanel20jMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel25jPanel20mouseenered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel25jPanel20exited(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 102, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/icons8_logout_rounded_left_1px_2.png"))); // NOI18N
        jLabel21.setText("Log out");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jPanel4.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 190, 50));

        jPanel20.setBackground(new java.awt.Color(222, 215, 215));
        jPanel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel20jMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel20mouseenered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel20exited(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 17)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 102, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/Group-Message.png"))); // NOI18N
        jLabel22.setText(" Messages");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jPanel4.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 190, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 560));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/H.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jPanel5.setBackground(new java.awt.Color(228, 237, 237));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 850, 90));

        jTabbedPane1.setBackground(new java.awt.Color(228, 237, 237));

        jPanel2.setBackground(new java.awt.Color(228, 237, 237));
        jPanel2.setPreferredSize(new java.awt.Dimension(620, 536));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(228, 237, 237));
        jLabel3.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Customer ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 150, -1));

        jLabel4.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("First Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 160, -1));

        jLabel8.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Last Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Password");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 160, -1));

        jLabel5.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Checkin date");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Checkout date");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Phone Number");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 97, -1));

        jLabel10.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Total price");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 150, -1));
        jPanel2.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 160, -1));
        jPanel2.add(jDateChooser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 150, -1));

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 150, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/add11.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel14MouseReleased(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(228, 237, 237));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Password", "First name", "Second name", "Checkin date", "Checkout date", "Phone number", "Room no.", "Total proce"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(9);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(8);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(8);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(5);
        }

        jLabel11.setBackground(new java.awt.Color(228, 237, 237));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Customer ID");

        searchCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/search.png"))); // NOI18N
        searchCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchCustomerMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchCustomerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchCustomerMouseReleased(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/remove1.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel19MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel19MouseReleased(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/message1.png"))); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel26MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel26MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel26MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(38, 38, 38)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(searchCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchCustomer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel8.setBackground(new java.awt.Color(228, 237, 237));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton22.setBackground(new java.awt.Color(153, 153, 255));
        jButton22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton22.setForeground(new java.awt.Color(102, 102, 102));
        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png"))); // NOI18N
        jButton22.setText("207");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 130, 120));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 255));
        jLabel16.setText("Note: Rooms with even numbers are AC rooms , others are non AC ");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton23.setBackground(new java.awt.Color(153, 153, 255));
        jButton23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton23.setForeground(new java.awt.Color(102, 102, 102));
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png"))); // NOI18N
        jButton23.setText("100");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 130, 120));

        jButton24.setBackground(new java.awt.Color(153, 153, 255));
        jButton24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton24.setForeground(new java.awt.Color(102, 102, 102));
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png"))); // NOI18N
        jButton24.setText("101");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 130, 120));

        jButton25.setBackground(new java.awt.Color(153, 153, 255));
        jButton25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton25.setForeground(new java.awt.Color(102, 102, 102));
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png"))); // NOI18N
        jButton25.setText("102");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 130, 120));

        jButton26.setBackground(new java.awt.Color(153, 153, 255));
        jButton26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton26.setForeground(new java.awt.Color(102, 102, 102));
        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png"))); // NOI18N
        jButton26.setText("103");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 130, 120));

        jButton27.setBackground(new java.awt.Color(153, 153, 255));
        jButton27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton27.setForeground(new java.awt.Color(102, 102, 102));
        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png"))); // NOI18N
        jButton27.setText("104");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 130, 120));

        jButton28.setBackground(new java.awt.Color(153, 153, 255));
        jButton28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton28.setForeground(new java.awt.Color(102, 102, 102));
        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png"))); // NOI18N
        jButton28.setText("105");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 130, 120));

        jButton29.setBackground(new java.awt.Color(153, 153, 255));
        jButton29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton29.setForeground(new java.awt.Color(102, 102, 102));
        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png"))); // NOI18N
        jButton29.setText("106");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 130, 120));

        jButton30.setBackground(new java.awt.Color(153, 153, 255));
        jButton30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton30.setForeground(new java.awt.Color(102, 102, 102));
        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png"))); // NOI18N
        jButton30.setText("107");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 130, 120));

        jButton31.setBackground(new java.awt.Color(153, 153, 255));
        jButton31.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton31.setForeground(new java.awt.Color(102, 102, 102));
        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png"))); // NOI18N
        jButton31.setText("200");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 130, 120));

        jButton32.setBackground(new java.awt.Color(153, 153, 255));
        jButton32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton32.setForeground(new java.awt.Color(102, 102, 102));
        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png"))); // NOI18N
        jButton32.setText("201");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 130, 120));

        jButton33.setBackground(new java.awt.Color(153, 153, 255));
        jButton33.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton33.setForeground(new java.awt.Color(102, 102, 102));
        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png"))); // NOI18N
        jButton33.setText("202");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 130, 120));

        jButton34.setBackground(new java.awt.Color(153, 153, 255));
        jButton34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton34.setForeground(new java.awt.Color(102, 102, 102));
        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png"))); // NOI18N
        jButton34.setText("203");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 130, 120));

        jButton35.setBackground(new java.awt.Color(153, 153, 255));
        jButton35.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton35.setForeground(new java.awt.Color(102, 102, 102));
        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png"))); // NOI18N
        jButton35.setText("204");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 130, 120));

        jButton36.setBackground(new java.awt.Color(153, 153, 255));
        jButton36.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton36.setForeground(new java.awt.Color(102, 102, 102));
        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png"))); // NOI18N
        jButton36.setText("205");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 130, 120));

        jButton37.setBackground(new java.awt.Color(153, 153, 255));
        jButton37.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton37.setForeground(new java.awt.Color(102, 102, 102));
        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png"))); // NOI18N
        jButton37.setText("206");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 130, 120));

        jScrollPane2.setViewportView(jPanel8);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel7);

        jPanel10.setBackground(new java.awt.Color(228, 237, 237));

        jLabel25.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 102, 255));
        jLabel25.setText("Here are messages to you from the adminstration :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel6);

        jPanel12.setBackground(new java.awt.Color(228, 237, 237));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab6", jPanel12);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 850, 420));

        panel16.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout panel16Layout = new javax.swing.GroupLayout(panel16);
        panel16.setLayout(panel16Layout);
        panel16Layout.setHorizontalGroup(
            panel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel16Layout.setVerticalGroup(
            panel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(panel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 5, 570));

        panel6.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(panel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 5, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1090, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exited

        if(evt.getSource()==jPanel9)
        jPanel9.setBackground(new Color(222,215,215));
        // TODO add your handling code here:
    }//GEN-LAST:event_exited

    private void mouseenered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseenered

        if(evt.getSource()==jPanel9)
        jPanel9.setBackground(new Color(204,204,204));
        // TODO add your handling code here:
    }//GEN-LAST:event_mouseenered

    private void jPanel15exited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15exited
        if(evt.getSource()==jPanel15)
        jPanel15.setBackground(new Color(222,215,215));
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel15exited

    private void jPanel15mouseenered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15mouseenered
        if(evt.getSource()==jPanel15)
        jPanel15.setBackground(new Color(204,204,204));
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel15mouseenered

    private void jPanel19exited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19exited

        if(evt.getSource()==jPanel19)
        jPanel19.setBackground(new Color(222,215,215));
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel19exited

    private void jPanel19mouseenered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19mouseenered
        if(evt.getSource()==jPanel19)
        jPanel19.setBackground(new Color(204,204,204));  // TODO add your handling code here:
    }//GEN-LAST:event_jPanel19mouseenered

    private void jMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMouseClicked
    
if(evt.getSource()==jPanel9)
    {
    jTabbedPane1.setSelectedIndex(0);
  
    }
 else if(evt.getSource()==jPanel15)
    {
jTabbedPane1.setSelectedIndex(1);
    }

 else if(evt.getSource()==jPanel19)
 {
     jTabbedPane1.setSelectedIndex(2);

 }
// TODO add your handling code here:
    }//GEN-LAST:event_jMouseClicked

    private void jPanel16jMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16jMouseClicked
jTabbedPane1.setSelectedIndex(4);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel16jMouseClicked

    private void jPanel16mouseenered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16mouseenered
if(evt.getSource()==jPanel16)
        jPanel16.setBackground(new Color(204,204,204));         // TODO add your handling code here:
    }//GEN-LAST:event_jPanel16mouseenered

    private void jPanel16exited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16exited
       if(evt.getSource()==jPanel16)
        jPanel16.setBackground(new Color(222,215,215));  // TODO add your handling code here:
    }//GEN-LAST:event_jPanel16exited

    private void jPanel25jPanel20jMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel25jPanel20jMouseClicked
       NewJFrame j=new NewJFrame();
       j.setVisible(true);
       this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jPanel25jPanel20jMouseClicked

    private void jPanel25jPanel20mouseenered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel25jPanel20mouseenered
       if(evt.getSource()==jPanel25)
        jPanel25.setBackground(new Color(204,204,204));  // TODO add your handling code here:
    }//GEN-LAST:event_jPanel25jPanel20mouseenered

    private void jPanel25jPanel20exited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel25jPanel20exited
     if(evt.getSource()==jPanel25)
        jPanel25.setBackground(new Color(222,215,215));    // TODO add your handling code here:
    }//GEN-LAST:event_jPanel25jPanel20exited

    private void jPanel20jMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20jMouseClicked

        if(evt.getSource()==jPanel20)
        {
            jTabbedPane1.setSelectedIndex(3);

        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel20jMouseClicked

    private void jPanel20mouseenered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20mouseenered
        if(evt.getSource()==jPanel20)
        jPanel20.setBackground(new Color(204,204,204));  // TODO add your handling code here:
    }//GEN-LAST:event_jPanel20mouseenered

    private void jPanel20exited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20exited

        if(evt.getSource()==jPanel20)
        jPanel20.setBackground(new Color(222,215,215));
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel20exited

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        Room1 R1=new Room1();
        R1.setVisible(true);
        R1.jLabel1.setText("Room #206");
        R1.jLabel3.setText("Non AC");

        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/icons8_lock_50px_1.png"));

        if(jButton37.getBackground().equals(new Color(51,204,255))){
            R1.jTextField1.setText("Available");
            jButton37.setBackground(new Color(153,153,255));
            jButton37.setIcon(new ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png")));
        }

        else if(jButton37.getBackground().equals(new Color(153,153,255)))
        {        R1.jTextField1.setText("Booked");
            jButton37.setIcon(II);

            jButton37.setBackground(new Color(51,204,255));

        }
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        Room1 R2=new Room1();
        R2.setVisible(true);
        R2.jLabel1.setText("Room #205");
        R2.jLabel3.setText("Non AC");

        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/icons8_lock_50px_1.png"));

        if(jButton36.getBackground().equals(new Color(51,204,255))){
            R2.jTextField1.setText("Available");
            jButton36.setBackground(new Color(153,153,255));
            jButton36.setIcon(new ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png")));
        }

        else if(jButton36.getBackground().equals(new Color(153,153,255)))
        {        R2.jTextField1.setText("Booked");
            jButton36.setIcon(II);

            jButton36.setBackground(new Color(51,204,255));

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        Room1 R1=new Room1();
        R1.setVisible(true);
        R1.jLabel1.setText("Room #204");
        R1.jLabel3.setText("Non AC");
        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/icons8_lock_50px_1.png"));

        if(jButton35.getBackground().equals(new Color(51,204,255))){
            R1.jTextField1.setText("Available");
            jButton35.setBackground(new Color(153,153,255));
            jButton35.setIcon(new ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png")));
        }

        else if(jButton35.getBackground().equals(new Color(153,153,255)))
        {        R1.jTextField1.setText("Booked");
            jButton35.setIcon(II);

            jButton35.setBackground(new Color(51,204,255));

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        Room1 R2=new Room1();
        R2.setVisible(true);
        R2.jLabel1.setText("Room #203");
        R2.jLabel3.setText("Non AC");

        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/icons8_lock_50px_1.png"));

        if(jButton34.getBackground().equals(new Color(51,204,255))){
            R2.jTextField1.setText("Available");
            jButton34.setBackground(new Color(153,153,255));
            jButton34.setIcon(new ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png")));
        }

        else if(jButton34.getBackground().equals(new Color(153,153,255)))
        {        R2.jTextField1.setText("Booked");
            jButton34.setIcon(II);

            jButton34.setBackground(new Color(51,204,255));

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        Room1 R1=new Room1();
        R1.setVisible(true);
        R1.jLabel1.setText("Room #202");

        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/icons8_lock_50px_1.png"));

        if(jButton33.getBackground().equals(new Color(51,204,255))){
            R1.jTextField1.setText("Available");
            jButton33.setBackground(new Color(153,153,255));
            jButton33.setIcon(new ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png")));
        }

        else if(jButton33.getBackground().equals(new Color(153,153,255)))
        {        R1.jTextField1.setText("Booked");
            jButton33.setIcon(II);

            jButton33.setBackground(new Color(51,204,255));

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        Room1 R2=new Room1();
        R2.setVisible(true);
        R2.jLabel1.setText("Room #201");
        R2.jLabel3.setText("Non AC");

        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/icons8_lock_50px_1.png"));

        if(jButton32.getBackground().equals(new Color(51,204,255))){
            R2.jTextField1.setText("Available");
            jButton32.setBackground(new Color(153,153,255));
            jButton32.setIcon(new ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png")));
        }

        else if(jButton32.getBackground().equals(new Color(153,153,255)))
        {        R2.jTextField1.setText("Booked");
            jButton32.setIcon(II);

            jButton32.setBackground(new Color(51,204,255));

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        Room1 R1=new Room1();
        R1.setVisible(true);
        R1.jLabel1.setText("Room #200");

        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/icons8_lock_50px_1.png"));

        if(jButton31.getBackground().equals(new Color(51,204,255))){
            R1.jTextField1.setText("Available");
            jButton31.setBackground(new Color(153,153,255));
            jButton31.setIcon(new ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png")));
        }

        else if(jButton31.getBackground().equals(new Color(153,153,255)))
        {        R1.jTextField1.setText("Booked");
            jButton31.setIcon(II);

            jButton31.setBackground(new Color(51,204,255));

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        Room1 R2=new Room1();
        R2.setVisible(true);
        R2.jLabel1.setText("Room #107");
        R2.jLabel3.setText("Non AC");

        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/icons8_lock_50px_1.png"));

        if(jButton30.getBackground().equals(new Color(51,204,255))){
            R2.jTextField1.setText("Available");
            jButton30.setBackground(new Color(153,153,255));
            jButton30.setIcon(new ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png")));
        }

        else if(jButton30.getBackground().equals(new Color(153,153,255)))
        {        R2.jTextField1.setText("Booked");
            jButton30.setIcon(II);

            jButton30.setBackground(new Color(51,204,255));

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed

        Room1 R1=new Room1();
        R1.setVisible(true);
        R1.jLabel1.setText("Room #106");

        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/icons8_lock_50px_1.png"));

        if(jButton29.getBackground().equals(new Color(51,204,255))){
            R1.jTextField1.setText("Available");
            jButton29.setBackground(new Color(153,153,255));
            jButton29.setIcon(new ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png")));
        }

        else if(jButton29.getBackground().equals(new Color(153,153,255)))
        {        R1.jTextField1.setText("Booked");
            jButton29.setIcon(II);

            jButton29.setBackground(new Color(51,204,255));

        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        Room1 R2=new Room1();
        R2.setVisible(true);
        R2.jLabel1.setText("Room #105");
        R2.jLabel3.setText("Non AC");

        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/icons8_lock_50px_1.png"));

        if(jButton28.getBackground().equals(new Color(51,204,255))){
            R2.jTextField1.setText("Available");
            jButton28.setBackground(new Color(153,153,255));
            jButton28.setIcon(new ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png")));
        }

        else if(jButton28.getBackground().equals(new Color(153,153,255)))
        {        R2.jTextField1.setText("Booked");
            jButton28.setIcon(II);

            jButton28.setBackground(new Color(51,204,255));

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        Room1 R1=new Room1();
        R1.setVisible(true);
        R1.jLabel1.setText("Room #104");

        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/icons8_lock_50px_1.png"));

        if(jButton27.getBackground().equals(new Color(51,204,255))){
            R1.jTextField1.setText("Available");
            jButton27.setBackground(new Color(153,153,255));
            jButton27.setIcon(new ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png")));
        }

        else if(jButton27.getBackground().equals(new Color(153,153,255)))
        {        R1.jTextField1.setText("Booked");
            jButton27.setIcon(II);

            jButton27.setBackground(new Color(51,204,255));

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        Room1 R2=new Room1();
        R2.setVisible(true);
        R2.jLabel1.setText("Room #103");
        R2.jLabel3.setText("Non AC");

        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/icons8_lock_50px_1.png"));

        if(jButton26.getBackground().equals(new Color(51,204,255))){
            R2.jTextField1.setText("Available");
            jButton26.setBackground(new Color(153,153,255));
            jButton26.setIcon(new ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png")));
        }

        else if(jButton26.getBackground().equals(new Color(153,153,255)))
        {        R2.jTextField1.setText("Booked");
            jButton26.setIcon(II);

            jButton26.setBackground(new Color(51,204,255));

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        Room1 R1=new Room1();
        R1.setVisible(true);
        R1.jLabel1.setText("Room #102");

        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/icons8_lock_50px_1.png"));

        if(jButton25.getBackground().equals(new Color(51,204,255))){
            R1.jTextField1.setText("Available");
            jButton25.setBackground(new Color(153,153,255));
            jButton25.setIcon(new ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png")));
        }

        else if(jButton25.getBackground().equals(new Color(153,153,255)))
        {        R1.jTextField1.setText("Booked");
            jButton25.setIcon(II);

            jButton25.setBackground(new Color(51,204,255));

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        Room1 R2=new Room1();
        R2.setVisible(true);
        R2.jLabel1.setText("Room #101");
        R2.jLabel3.setText("Non AC");

        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/icons8_lock_50px_1.png"));

        if(jButton24.getBackground().equals(new Color(51,204,255))){
            R2.jTextField1.setText("Available");
            jButton24.setBackground(new Color(153,153,255));
            jButton24.setIcon(new ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png")));
        }

        else if(jButton24.getBackground().equals(new Color(153,153,255)))
        {        R2.jTextField1.setText("Booked");
            jButton24.setIcon(II);

            jButton24.setBackground(new Color(51,204,255));

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        Room1 R1=new Room1();
        R1.setVisible(true);
        R1.jLabel1.setText("Room #100");
        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/icons8_lock_50px_1.png"));

        if(jButton23.getBackground().equals(new Color(51,204,255))){
            R1.jTextField1.setText("Available");
            jButton23.setBackground(new Color(153,153,255));
            jButton23.setIcon(new ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png")));
        }

        else if(jButton23.getBackground().equals(new Color(153,153,255)))
        {        R1.jTextField1.setText("Booked");
            jButton23.setIcon(II);

            jButton23.setBackground(new Color(51,204,255));

        }
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        Room1 R2=new Room1();
        R2.setVisible(true);
        R2.jLabel1.setText("Room #207");
        R2.jLabel3.setText("Non AC");

        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/icons8_lock_50px_1.png"));

        if(jButton22.getBackground().equals(new Color(51,204,255))){
            R2.jTextField1.setText("Available");
            jButton22.setBackground(new Color(153,153,255));
            jButton22.setIcon(new ImageIcon(getClass().getResource("/hotelide/icons8_unlock_50px_2.png")));
        }

        else if(jButton22.getBackground().equals(new Color(153,153,255)))
        {        R2.jTextField1.setText("Booked");
            jButton22.setIcon(II);

            jButton22.setBackground(new Color(51,204,255));

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jLabel19MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseReleased
        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/remove2.png"));
        jLabel19.setIcon(II);          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseReleased

    private void jLabel19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MousePressed
        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/remove3.png"));
        jLabel19.setIcon(II);          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MousePressed

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/remove1.png"));
        jLabel19.setIcon(II);          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseExited

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered

        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/remove2.png"));
        jLabel19.setIcon(II);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseEntered

    private void searchCustomerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchCustomerMouseReleased
        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/search2.png"));
        searchCustomer.setIcon(II);
        // TODO add your handling code here:
    }//GEN-LAST:event_searchCustomerMouseReleased

    private void searchCustomerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchCustomerMousePressed

        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/searchhh.png"));
        searchCustomer.setIcon(II);// TODO add your handling code here:
    }//GEN-LAST:event_searchCustomerMousePressed

    private void searchCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchCustomerMouseExited
        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/search.png"));
        searchCustomer.setIcon(II);
        // TODO add your handling code here:
    }//GEN-LAST:event_searchCustomerMouseExited

    private void searchCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchCustomerMouseEntered
        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/search2.png"));
        searchCustomer.setIcon(II);        // TODO add your handling code here:
    }//GEN-LAST:event_searchCustomerMouseEntered

    private void jLabel14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseReleased
        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/add22.png"));
        jLabel14.setIcon(II);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseReleased

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/add33.png"));
        jLabel14.setIcon(II);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MousePressed

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/add11.png"));
        jLabel14.setIcon(II);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/add22.png"));
        jLabel14.setIcon(II);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        Messages M=new Messages();
        M.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseEntered
        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/message2.png"));
        jLabel26.setIcon(II);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MouseEntered

    private void jLabel26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseExited
        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/message1.png"));
        jLabel26.setIcon(II);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MouseExited

    private void jLabel26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MousePressed
        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/message3.png"));
        jLabel26.setIcon(II);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MousePressed

    private void jLabel26MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseReleased
        ImageIcon II= new ImageIcon(getClass().getResource("/hotelide/message2.png"));
        jLabel26.setIcon(II);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MouseReleased
   
   
    
    
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmRes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton22;
    public javax.swing.JButton jButton23;
    public javax.swing.JButton jButton24;
    public javax.swing.JButton jButton25;
    public javax.swing.JButton jButton26;
    public javax.swing.JButton jButton27;
    public javax.swing.JButton jButton28;
    public javax.swing.JButton jButton29;
    public javax.swing.JButton jButton30;
    public javax.swing.JButton jButton31;
    public javax.swing.JButton jButton32;
    public javax.swing.JButton jButton33;
    public javax.swing.JButton jButton34;
    public javax.swing.JButton jButton35;
    public javax.swing.JButton jButton36;
    public javax.swing.JButton jButton37;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.awt.Panel panel16;
    private java.awt.Panel panel6;
    private javax.swing.JLabel searchCustomer;
    // End of variables declaration//GEN-END:variables

}
